export enum QueryKeys {
  MODERATION_VIEW = 'MODERATION_VIEW',
  PRODUCT_CATEGORIES = 'PRODUCT_CATEGORIES',
  PRODUCT_VIEW = 'PRODUCT_VIEW',
  PROFILE = 'PROFILE',
  SERVICE_CATEGORIES = 'SERVICE_CATEGORIES',
  USER_VIEW = 'USER_VIEW',
}
