export enum QueryKeys {
  NEWS = 'NEWS',
  PRODUCTS_VIEW = 'PRODUCTS_VIEW',
  PRODUCT_CATEGORIES = 'PRODUCT_CATEGORIES',
  PRODUCT_VIEW = 'PRODUCT_VIEW',
  PROFILE = 'PROFILE',
  SERVICE_CATEGORIES = 'SERVICE_CATEGORIES',
  SERVICE_LIST = 'SERVICE_LIST',
  SERVICE_VIEW = 'SERVICE_VIEW',
  USER_VIEW = 'USER_VIEW',
}
