export type RbacValueKey =
  | 'DELETE quick-iiko/{id}'
  | 'DELETE quick-resto/{id}'
  | 'GET '
  | 'GET /{id}'
  | 'POST iiko'
  | 'POST quick-resto'
  | 'PUT iiko/{id}'
  | 'PUT quick-resto/{id}'
  | 'DELETE /{id}'
  | 'POST '
  | 'PUT /{id}'
  | 'GET city'
  | 'GET country'
  | 'POST upload-banner/{id}'
  | 'DELETE '
  | 'POST close/{id}'
  | 'POST upload-multiple/{id}'
  | 'POST upload/{id}'
  | 'upload-document/{id}'
  | 'delete-document/{id}'
  | string;

export type RbacKeys =
  | 'account-system'
  | 'contract'
  | 'dictionary'
  | 'guest'
  | 'institution-table'
  | 'institution'
  | 'knowledge-base-article'
  | 'knowledge-base-category'
  | 'knowledge-base-section'
  | 'news-events'
  | 'news-events-version'
  | 'partner'
  | 'rbac'
  | 'support-chat'
  | 'support-message'
  | 'user'
  | 'table-tag'
  | string;

export type Rbac = Record<RbacKeys, Record<RbacValueKey, boolean>>;
