export enum QueryKeys {
  booking = 'booking',
  bookingView = 'booking-view',
  categoryView = 'category-view',
  contract = 'contract',
  contracts = 'contracts',
  dadataAddress = 'dadata-address',
  dictionaryCity = 'dictionary-city',
  dictionaryCountry = 'dictionary-country',
  dictionaryReservationStatus = 'dictionary-reservation-status',
  events = 'events',
  guests = 'guests',
  institution = 'institution',
  institutionTable = 'institution-table',
  institutionTables = 'institution-tables',
  institutions = 'institutions',
  institutionsView = 'institutions-view',
  news = 'news',
  partnerView = 'partner-view',
  promoCodes = 'promo-codes',
  rbac = 'rbac',
  staff = 'staff',
  tags = 'tags',
  users = 'users',
}
